---
title: "Beginners guide to publishing your code in Bioconductor"
output: html_notebook
---

*Guide to Making a Bioconductor Package*

* Day 1 *



1. Organization of files
* Data
   + Raw Data (Saving Download info, reproducible, BiocFileCache)
   + QC/processing
   + Final "polished data"
   + Checksum (how to check for data integrity)
  
 * Code organization
    + skeleton
    + Roxygen
    + unit tests
    
2. Very brief overview of Bioc/R classes
 + S3 v S4 
 + Core classes in Bioc  (SummarizedExperiment)
 + Beware of conflicts with HadleyVerse  (package conflicted)

3. Coding style 
+ Bioconductor, Google style books

4. Create a simple package 
+ Check, Build



* Day 2*     
1. Dummies guide to github
 
2. Making a good vignette
+ Sample v real data
+ data packages (and size limits)
+ How to manage when data comes from external resources (eg restfulSE)

3. AnnotationHub, ExperimentHub

3. Check, build, BiocCheck
+ error
+ warning
+ style

4. Man Pages (Roxygen)

5. Submitting to Bioc
+ Packages cycle
+ Devel/Release how it works
+ Versioning

6. Github for Bioconductor
+ Mirror
+ Pull requests
+ Make changes to released version

7. Basic RShiny for Bioconductor -interactiveDisplay
8. HadleyVerse in Bioconductor - plyranges, BioBroom 


    
        
  

   
    
